// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @enum {number}
 */
export namespace Switchboard{
export enum FeedType{
  Default= 0,
  Trade= 1,
  Liquidation= 2
}};

/**
 * @enum {number}
 */
export namespace Switchboard{
export enum Side{
  Sell= -1,
  None= 0,
  Buy= 1
}};

/**
 * @enum {number}
 */
export namespace Switchboard{
export enum SubReqType{
  Subscribe= 1,
  Unsubscribe= 2
}};

