// automatically generated by the FlatBuffers compiler, do not modify

import * as NS6402863256139227694 from "./LiquidationOrder_generated";
export namespace Switchboard { 
export import LiquidationOrder = NS6402863256139227694.Switchboard.LiquidationOrder; }
import * as NS6823633475464199631 from "./SessionStatus_generated";
export namespace Switchboard { 
export import SessionStatus = NS6823633475464199631.Switchboard.SessionStatus; }
import * as NS584072177544900616 from "./PublicTrade_generated";
export namespace Switchboard { 
export import PublicTrade = NS584072177544900616.Switchboard.PublicTrade; }
import * as NS13677774665957090232 from "./FeedRequest_generated";
export namespace Switchboard { 
export import FeedRequest = NS13677774665957090232.Switchboard.FeedRequest; }
import * as NS4318123797752956812 from "./FeedRequestAccept_generated";
export namespace Switchboard { 
export import FeedRequestAccept = NS4318123797752956812.Switchboard.FeedRequestAccept; }
import * as NS2618412122345160958 from "./MDSnapshotL2_generated";
export namespace Switchboard { 
export import MDSnapshotL2 = NS2618412122345160958.Switchboard.MDSnapshotL2; }
import * as NS3180374600874012547 from "./FeedRequestReject_generated";
export namespace Switchboard { 
export import FeedRequestReject = NS3180374600874012547.Switchboard.FeedRequestReject; }
/**
 * @enum {number}
 */
export namespace Switchboard{
export enum Body{
  NONE= 0,
  FeedRequest= 1,
  FeedRequestAccept= 2,
  FeedRequestReject= 3,
  MDSnapshotL2= 4,
  PublicTrade= 5,
  SessionStatus= 6,
  LiquidationOrder= 7
}};

/**
 * @constructor
 */
export namespace Switchboard{
export class Message {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Message
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Message {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Message= obj
 * @returns Message
 */
static getRoot(bb:flatbuffers.ByteBuffer, obj?:Message):Message {
  return (obj || new Message()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Message= obj
 * @returns Message
 */
static getSizePrefixedRoot(bb:flatbuffers.ByteBuffer, obj?:Message):Message {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Message()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @returns boolean
 */
static bufferHasIdentifier(bb:flatbuffers.ByteBuffer):boolean {
  return bb.__has_identifier('RMP1');
};

/**
 * @returns flatbuffers.Long
 */
tts():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @returns Switchboard.Body
 */
bodyType():Switchboard.Body {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : Switchboard.Body.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
body<T extends flatbuffers.Table>(obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static start(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long tts
 */
static addTts(builder:flatbuffers.Builder, tts:flatbuffers.Long) {
  builder.addFieldInt64(0, tts, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param Switchboard.Body bodyType
 */
static addBodyType(builder:flatbuffers.Builder, bodyType:Switchboard.Body) {
  builder.addFieldInt8(1, bodyType, Switchboard.Body.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset bodyOffset
 */
static addBody(builder:flatbuffers.Builder, bodyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, bodyOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static end(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'RMP1');
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishSizePrefixedBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'RMP1', true);
};

static create(builder:flatbuffers.Builder, tts:flatbuffers.Long, bodyType:Switchboard.Body, bodyOffset:flatbuffers.Offset):flatbuffers.Offset {
  Message.start(builder);
  Message.addTts(builder, tts);
  Message.addBodyType(builder, bodyType);
  Message.addBody(builder, bodyOffset);
  return Message.end(builder);
}
}
}
