// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReactiveMarkets.Switchboard
{

public enum SubReqType : sbyte
{
  Subscribe = 1,
  Unsubscribe = 2,
};


}
